### ISSUE TITLE
Problème accents

### ISSUE THREAD

**Issue by tmartin6** [aripot007/auto-survival-guide#3]
Les accents ne sont pas pris en compte dans la génération du fichier et dans l'exécution du script python

``` bash
Fetching latest guide from api.survival-guide.tk ...
Searching words definitions ...

Avertissement : le mot 'L'affaire du siÃ¨cle' n'a été trouvé dans aucune des sources données.
Entrez une manuellement pour 'L'affaire du siÃ¨cle' ('s' = passer ce mot) :

```

**Comment by aripot007** [comment]
J'avais vu ça (#2 ), je sais pas exactement d'où ça vient, je regarderais ça quand j'aurais un peu plus de temps.
J'ai testé sur 2 pc différents et sur un les accents s'affichent correctement, mais dans tout les cas le programme trouve pas de définition pour L'affaire du siècle car il n'y a pas de page en anglais sur wikipédia pour ça.
